create database sql_basic

---DATA PREPARATION AND UNDERSTANDING

---Q1 BEGIN-- What is the total number of rows in each of the 3 tables in the database?
	Select count(customer_Id) from Customer
	Select count(transaction_id) from Transactions
	Select count(prod_cat_code) from prod_cat_info

---Q1 END



---Q2 BEGIN --What is the total number of transactions that have a return?

	select count(transaction_id)[Transations]from transactions
	where Qty<0
---Q2 END



---Q3 BEGIN-- As you would have noticed, the dates provided across the datasets are not in a correct format.
   -- As first steps, pls convert the date variables into valid date formats before proceeding ahead

   Alter table Transactions alter column tran_date date

---Q3 END



---Q4 BEGIN-- What is the time range of the transaction data available for analysis? 
      -- Show the output in number of days, months and years simultaneously in different columns.
SELECT DATEDIFF(DAY,MIN(tran_date),MAX(tran_date))[No. of Days],
       DATEDIFF(Month,MIN(tran_date),MAX(tran_date))[No.of Months],
       DATEDIFF(year,MIN(tran_date),MAX(tran_date))[No. of years] 
FROM transactions

---Q4 END



---Q5 BEGIN-- Which product category does the sub-category “DIY” belong to?
	select prod_cat from prod_cat_info
	where prod_subcat ='DIY'

---Q5 END



---DATA ANALYSIS

---Q1 BEGIN-- Which channel is most frequently used for transactions?
	select top 1 Store_type ,count(Store_type)[No. of transactions] from [dbo].[Transactions]
	group by store_type
	order by store_type

---Q1 END



---Q2 BEGIN-- What is the count of Male and Female customers in the database?

	select Gender,count(gender) [Count of gender]  from [dbo].[Customer]
	group by Gender
	having Gender = 'M' OR Gender= 'F'

---Q2 END



---Q3 BEGIN-- From which city do we have the maximum number of customers and how many?

	select top 1 count(customer_id)[Total customers],city_code from customer 
	group by city_code
	order by count(customer_id) desc

---Q3 END

---Q4 BEGIN-- How many sub-categories are there under the Books category?
	select count(Distinct(prod_subcat))[No. of sub_cat] from prod_cat_info
	WHERE PROD_CAT='Books'

---Q4 END



---Q5 BEGIN-- What is the maximum quantity of products ever ordered?
    select max(Qty)[Max order] from transactions

---Q5 END



---Q6 BEGIN-- What is the net total revenue generated in categories Electronics and Books?
	select p.prod_cat,Sum(t.total_amt)[Net Revenue] from transactions t 
	inner join prod_cat_info p on p.prod_sub_cat_code = t.prod_subcat_code and p.prod_cat_code = t.prod_cat_code
	Group By p.prod_cat
	Having p.prod_cat in('Electronics','Books')

---Q6 END



---Q7 BEGIN-- How many customers have >10 transactions with us, excluding returns?

select count(Cust_id) [No. of   customers] from
      (
	  select cust_id[Cust_id],count(Qty)[count of transactions] from transactions where Qty>0
      Group By cust_id 
      having count(Qty)>10
	  )t1

---Q7 END



---Q8 BEGIN-- What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

	 Select sum(total_amt)[Revenue] from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
	 and t.prod_subcat_code=p.prod_sub_cat_code
	 where Store_type ='Flagship store' and 
	 prod_cat in ('Electronics','Clothing')

---Q8 END



---Q9 BEGIN What is the total revenue generated from “Male” customers in “Electronics” category?
  ---Output should display total revenue by prod sub-cat

	 Select distinct prod_subcat,sum(total_amt)[Total Revenue] from Transactions t 
	 inner join prod_cat_info p on t.prod_subcat_code=p.prod_sub_cat_code
	 inner join Customer c on t.cust_id=c.customer_Id
	 where prod_cat='Electronics' and gender='M'
	 group by p.prod_subcat

---Q9 END


---Q10 BEGIN-- What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

Select t1.prod_subcat,[Percent sales],[Percent returns] from
 (Select top 5 prod_subcat,sum(total_amt) /(select sum(total_amt) from Transactions)*100[Percent sales] 
 from Transactions t 
 inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
 group by prod_sub_cat_code, prod_subcat
 order by sum(total_amt) desc)t1
 left join
 (Select top 5 p.prod_subcat,sum(qty)/(Select sum(qty)*0.01 from Transactions where qty<0)[Percent returns]
 from Transactions t2 inner join  prod_cat_info p on t2.prod_cat_code = p.prod_cat_code
 where Qty<0
 group by prod_sub_cat_code, prod_subcat
 order by [Percent returns] desc)t2 on t1.prod_subcat=t2.prod_subcat

---Q10 END



---Q11 BEGIN--For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of 
  ---transactions from max transaction date available in the data?

	select sum(total_amt)[Net revenue]  from Transactions t inner join (select *,datediff(year,DOB,getdate())[age]
	from  Customer)c on c.customer_id=t.cust_id
	where age between '25' and '35' and tran_date > DATEADD(day,-30,(select max(tran_date) from Transactions))


---Q11 END


---Q12 BEGIN--Which product category has seen the max value of returns in the last 3 months of transactions?

	select top 1 prod_cat from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
	where tran_date between dateadd(month,-3,(select max(tran_date) from transactions)) 
	and (select max(tran_date) from transactions) and qty<0
	group by prod_cat
	order by sum(qty) desc

--- Q12 END


---Q13 BEGIN--	Which store-type sells the maximum products; by value of sales amount and by quantity sold?

	 Select top 1 Store_type,sum(total_amt)[Sales Valuet], sum(qty)[Quantity] from Transactions 
	 group by Store_type
	 order by [Sales Valuet] desc,[Quantity]desc

---Q13 END



---Q14 BEGIN--	What are the categories for which average revenue is above the overall average.

	 Select prod_cat from Transactions t inner join prod_cat_info p
	 on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
	 group by t.prod_cat_code,prod_cat
	 having AVG(total_amt) > (Select AVG(total_amt) from Transactions)

---Q14 END



---Q15 BEGIN--	Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

	with cte as
	(select top 5 prod_cat_code from Transactions
	group by prod_cat_code
	order by sum(Qty) desc)

	 Select avg(total_amt)[Avg Revenue],sum(total_amt)[Total Revenue],prod_subcat from Transactions t inner join 
	 prod_cat_info p on t.prod_subcat_code=p.prod_sub_cat_code and t.prod_cat_code = p.prod_cat_code
	 where t. prod_cat_code in(Select * from cte)
	 group by prod_subcat


---Q15 END






	




